Issue-35 Accept Primary Key
rails/globalid pull request #136
Opened 2021-08-02 11:54 UTC by amerritt14

WIP PR

- Allow a primary_key argument
- Switch to find_by instead of find
- Only encode primary_key in uri if it is not id
- Start to adjust tests

2023-01-03 20:07 UTC, rafaelfranca requested changes

2023-01-03 20:07 UTC, rafaelfranca commented on lib/global_id/uri/gid.rb
> +        path_components.insert(2, parts[:primary_key]) unless parts[:primary_key].to_s == "id"
What kind of URL would this generate? We have no test for this in this branch.

2023-08-31 15:28 UTC, rafaelfranca commented
Support to custom primary keys should be already on the main branch. Let us know if that doesn't work for your use case. Thank you

2023-08-31 15:28 UTC, closed without merging

2023-08-31 16:02 UTC, amerritt14 commented
> Support to custom primary keys should be already on the main branch. Let us know if that doesn't work for your use case. Thank you

Thank you!